### PR TITLE
Total energy

### PR DESCRIPTION
**Pull request by mec07**
- Add a function to calculate the total energy.
- Add CI (i.e. automated tests and test coverage)

### CODE REVIEW

**Comment by mec07** [comment]
@horsfielda Interestingly enough, I noticed that the code doesn't run when you set the Hamiltonian to `collinear` because it says it can't find the model. This has probably been broken for a while. Do you know which model it used to use? Probably `TBexp.py`, right?

**Comment by horsfielda** [comment]
Originally I just had parameters in a dictionary I think. The models were 
something you and Max introduced. It may be that the collinear mabgnetism never 
worked! I used non-collinear in the one and only calculation I did.

**Comment by mec07** [comment]
@horsfielda I'm happy with this pull request now. It's worth you having a quick look over. I've got the tests running in CircleCI and the code coverage is being reported to codecov.io. There is no "base" coverage to compare against yet --  there will be once I've merged this into master. Do check out the coverage diff though: https://codecov.io/gh/mec07/PyLATO/pull/6/diff. I did a bit of a refactor in `pylato/hamiltonian.py`, but because I've gotten good code coverage from the tests, I'm not worried about having broken anything.

**Comment by horsfielda** [comment]
I have checked out the latest code. The tests run fine, but I cannot see how to 
run a program. pylato.py seems to have vanished.

**Comment by mec07** [comment]
Hi Andrew,

I made a mistake in this PR, which the next PR fixes. I had to move
PyLATO.py to main.py due to some naming conflicts (the package file is also
called pylato).

Marc

**Pull request merged**
